### ISSUE TITLE
关于指示条功能的建议，赶紧进来点赞啦！

### ISSUE THREAD

**Issue by 5536086** [naiba/nezha#10]
建议：**指示条占用50%以下为绿色，51%-80%为橙色显示，81%以上为红色显示，颜色自然渐变**，这样更醒目，一眼就能知道哪台资源占用过高了，作者说支持的人多了就给加上这个功能，哈哈

**Comment by brownchow** [comment]
感觉这个应该不难实现

**Comment by naiba** [comment]
> 感觉这个应该不难实现

有兴趣可以给这两套主题实现一下

**Comment by brownchow** [comment]
> > 感觉这个应该不难实现
> 
> 有兴趣可以给这两套主题实现一下

周末抽个时间写一下，提个PR

**Comment by naiba** [comment]
close at 13f90e7
