### ISSUE TITLE
甲骨文centos8被监控启动失败

### ISSUE THREAD

**Issue by po888375** [naiba/nezha#100]
### 描述问题 Describe the problem
大哥，我又来了，被监控的机子启动失败。

### 期待的结果 Expected result
解决办法

### 版本环境 Version environment

* 版本 Version：最新版
* 操作系统 Operating system：centos8
* 浏览器（如果使用）Browser (if used)：

**Comment by po888375** [comment]
`> 获取Agent日志
-- Logs begin at Wed 2021-02-24 08:17:04 GMT. --
Feb 25 03:24:12 instance-20210130-0914 systemd[1]: Stopped Nezha Agent.
-- Subject: Unit nezha-agent.service has finished shutting down
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- Unit nezha-agent.service has finished shutting down.
Feb 25 03:24:12 instance-20210130-0914 systemd[1]: Started Nezha Agent.
-- Subject: Unit nezha-agent.service has finished start-up
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- Unit nezha-agent.service has finished starting up.
-- 
-- The start-up result is done.
Feb 25 03:24:12 instance-20210130-0914 systemd[1]: nezha-agent.service: Main process exited, code=exited, status=203/EXEC
Feb 25 03:24:12 instance-20210130-0914 systemd[1]: nezha-agent.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- The unit nezha-agent.service has entered the 'failed' state with result 'exit-code'.
Feb 25 03:24:12 instance-20210130-0914 systemd[1]: nezha-agent.service: Service RestartSec=100ms expired, scheduling restart.
Feb 25 03:24:12 instance-20210130-0914 systemd[1]: nezha-agent.service: Scheduled restart job, restart counter is at 5.
-- Subject: Automatic restarting of a unit has been scheduled
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- Automatic restarting of the unit nezha-agent.service has been scheduled, as the result for
-- the configured Restart= setting for the unit.
Feb 25 03:24:12 instance-20210130-0914 systemd[1]: Stopped Nezha Agent.
-- Subject: Unit nezha-agent.service has finished shutting down
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- Unit nezha-agent.service has finished shutting down.
Feb 25 03:24:12 instance-20210130-0914 systemd[1]: nezha-agent.service: Start request repeated too quickly.
Feb 25 03:24:12 instance-20210130-0914 systemd[1]: nezha-agent.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- The unit nezha-agent.service has entered the 'failed' state with result 'exit-code'.
Feb 25 03:24:12 instance-20210130-0914 systemd[1]: Failed to start Nezha Agent.
-- Subject: Unit nezha-agent.service has failed
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- Unit nezha-agent.service has failed.
-- 
-- The result is failed.
`

**Comment by naiba** [comment]
`cd /opt/nezha/agent && ./nezha-agent` 截图

**Comment by po888375** [comment]
> `cd /opt/nezha/agent && ./nezha-agent` 截图
[root@instance-20210130-0914 ~]# cd /opt/nezha/agent && ./nezha-agent
Usage of ./nezha-agent:
  -d	允许不安全连接
  -i string
    	unused 旧Agent兼容
  -p string
    	Agent连接Secret
  -s string
    	管理面板RPC端口 (default "localhost:5555")
[root@instance-20210130-0914 agent]#

**Comment by naiba** [comment]
没啥问题呀，`systemctl start nezha-agent.service`

**Comment by po888375** [comment]
> 没啥问题呀，`systemctl start nezha-agent.service`

大佬，日志里报这个
The unit nezha-agent.service has entered the 'failed' state with result 'exit-code'.
Feb 25 03:41:33 instance-20210130-0914 systemd[1]: Failed to start Nezha Agent.
-- Subject: Unit nezha-agent.service has failed
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- Unit nezha-agent.service has failed.
-- 
-- The result is failed.

**Comment by naiba** [comment]
`./nezha-agent -d -p 密钥 -s nocdn.name:5555` 手动启动一下吧，这个得具体看为什么service启动不了，只能你自己研究了

**Comment by po888375** [comment]
> `./nezha-agent -d -p 密钥 -s nocdn.name:5555` 手动启动一下吧，这个得具体看为什么service启动不了，只能你自己研究了

那大哥，这是我另一台被监控报的问题，说是超时，但其他有两台又连接上了。
Feb 25 12:51:48 VM_0_7_centos nezha-agent[2403]: 2021/02/25 12:51:48 client.ReportSystemInfo err: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp ip:5555: i/o timeout"
Feb 25 12:51:48 VM_0_7_centos nezha-agent[2403]: 2021/02/25 12:51:48 Error to close connection ...
Feb 25 12:51:48 VM_0_7_centos nezha-agent[2403]: 2021/02/25 12:51:48 reportState error rpc error: code = Canceled desc = grpc: the client connection is closing
Feb 25 12:51:58 VM_0_7_centos nezha-agent[2403]: 2021/02/25 12:51:58 Try to reconnect ...

**Comment by po888375** [comment]
> `./nezha-agent -d -p 密钥 -s nocdn.name:5555` 手动启动一下吧，这个得具体看为什么service启动不了，只能你自己研究了

大佬，是安全组没开。现在好了

**Comment by po888375** [comment]
> `./nezha-agent -d -p 密钥 -s nocdn.name:5555` 手动启动一下吧，这个得具体看为什么service启动不了，只能你自己研究了

用命令手动启动就正常了

**Comment by naiba** [comment]
现在是没问题了吧

**Comment by po888375** [comment]
> 现在是没问题了吧

嗯嗯，我用screen手动启动，没问题了，对了，大哥，这个issue是被删了吗，我以后还能找到吗

**Comment by naiba** [comment]
Issue 无法删除的，在 closed 里面可以找到
