### ISSUE TITLE
当面板密钥手动修改后，agent无法连接

### ISSUE THREAD

**Issue by Es-dese** [naiba/nezha#104]
313 commits 面板，0.4.5 agent

当面板后台的密钥处手动修改后，agent无法连接log会提示验证失败

必须在脚本处重启面板，agent才可以连接上

另外请求加回agent的ID参数“-i”，方便查看时定位server文件是哪台，也可防止不小心生成重复密钥

**Comment by naiba** [comment]
最新代码没这问题，更新就完事了
