### ISSUE TITLE
备注内容太长了导致无法再次编辑

### ISSUE THREAD

**Issue by simplove** [naiba/nezha#105]
### 描述问题 Describe the problem
可能是在备注时面输入了过长的内容，导致该条记录无法编辑。其它的条目都是可以编辑的。

@naiba 

### 截屏或录像 Screenshot or video
截图如下：
https://vkceyugu.cdn.bspapp.com/VKCEYUGU-b1ebbd3c-ca49-405b-957b-effe60782276/ebc9cdde-811c-494c-9ac0-db9cc1e376e3.png
画红框的那个编辑按钮点了没有反应，其它的都可以。

### 版本环境 Version environment

* 版本 Version：v0.4.10
* 操作系统 Operating system：CentOS 7.3.1611
* 浏览器（如果使用）Browser (if used)： Chrome  88.0.4324.182

**Comment by naiba** [comment]
打开调试工具栏，点击按钮，截图看看错误

**Comment by simplove** [comment]
server:125 Uncaught SyntaxError: Invalid or unexpected token
