### ISSUE TITLE
更新后后台管理界面无法登陆

### ISSUE THREAD

**Issue by pplulee** [naiba/nezha#109]
### 描述问题 Describe the problem

升级到最新版本后， /server 后台管理界面无法登陆。错误信息：oauth2: server response missing access_token
使用最新安装脚本重新安装后问题仍然存在
config内以按照commit修改字段

返回URL内错误提示为The redirect_uri MUST match the registered callback URL for this application.
但在github OAuth application已配置回调URL
![image.png](https://i.loli.net/2021/03/05/smgRAr4F6XYExHo.png)

### 截屏或录像 Screenshot or video
![image.png](https://i.loli.net/2021/03/05/LQrGjD5NIkFUYh3.png)

### 版本环境 Version environment

* 版本 Version：v0.4.12
* 操作系统 Operating system：Centos7
* 浏览器（如果使用）Browser (if used)：Chrome

### 其他信息 Other information
管理面板使用了宝塔进行反代

**Comment by naiba** [comment]
按照以下步骤操作：

1. 看readme 确定脚本版本与面板版本均是最新
2. 使用脚本更新管理面板配置
3. 返回首页重新登录

**Comment by pplulee** [comment]
已解决，问题在反代上
反代时，发送域名需要与回调地址相同（原来是直接填localhost的）

**Comment by tin7safe** [comment]
我以上方法我也试过了，貌似都没用用，反代回调域名也填写了，还是
错误信息：该用户不是本站点管理员，无法登录
错误信息：oauth2: server response missing access_token

管理面板也重新配置过，很奇怪。
