### ISSUE TITLE
服务器在大陆及curl: (7) Failed to connect to raw.githubusercontent.com解决方案

### ISSUE THREAD

**Issue by guoyongchang** [naiba/nezha#11]
### 服务器在大陆：

脚本下载完后进行替换

```bash
sed -i 's/raw.githubusercontent.com/raw.staticdn.net/g' ./nezha.sh
sed -i 's/github.com/hub.fastgit.org/g' ./nezha.sh
```

### curl: (7) Failed to connect to raw.githubusercontent.com port 443: Connection refused

将以下内容写入hosts文件

```
199.232.68.133 raw.githubusercontent.com
```

### References

> https://github.com/hawtim/blog/issues/10
> https://blog.csdn.net/ybhuangfugui/article/details/108786498

**Comment by guoyongchang** [comment]
并不是百分百解决方案，hub.fastgit有时会进行检测

**Comment by naiba** [comment]
欢迎提交PR更新readme

**Comment by naiba** [comment]
或者更新脚本检测 http://api.myip.la/json 里面是china的话直接替换

**Comment by naiba** [comment]
> 或者更新脚本检测 http://api.myip.la/json 里面是china的话直接替换

已经集成到脚本里面了
