### ISSUE TITLE
关于客户端自动更新策略

### ISSUE THREAD

**Issue by xmxs** [naiba/nezha#111]
### 描述问题 Describe the problem
目前客户端默认会10min检查一次更新，是否可以支持传入参数，自定义更新间隔和是否启用自动更新呢？或者这个客户端自动更新的功能放到服务端，由服务端推送客户端的自动更新策略。

### 期待的结果 Expected result
客户端支持自定义更新间隔和开关自动更新；或由服务端推送客户端自动更新策略。

### 版本环境 Version environment

* 版本 Version：0.4.5
* 操作系统 Operating system：centos7.8
* 浏览器（如果使用）Browser (if used)：

**Comment by naiba** [comment]
近期比较忙，忙过去之后会重构，重构后可以查看历史数据。
也会取消 agent 自动更新

**Comment by xmxs** [comment]
> 近期比较忙，忙过去之后会重构，重构后可以查看历史数据。
> 也会取消 agent 自动更新

感谢naiba百忙之中的回复，哪吒探针真心是用过的ui和功能都相当舒服的探针了。

我自己改了一下agent的自动更新逻辑，编译了一份自用了，naiba先忙三次元吧。
