### ISSUE TITLE
关于服务监控的监控频率？

### ISSUE THREAD

**Issue by maker2002** [naiba/nezha#112]
请问下默认服务监控的监控频率是多久？如何调整监控频率？

**Comment by naiba** [comment]
Agent 3s上报一次

**Comment by maker2002** [comment]
> Agent 3s上报一次

谢谢，请问“服务”下的主动ping监控的频率呢？能否调整？

**Comment by naiba** [comment]
3分钟，目前不能调整

**Comment by maker2002** [comment]
> 3分钟，目前不能调整

再次感谢，请问下我也出现了这里提到的问题：https://github.com/naiba/nezha/issues/68
不管icmp ping还是tcp ping前台都显示故障。
有没有什么方法debug？

**Comment by maker2002** [comment]
> 3分钟，目前不能调整

关于我上面的问题，有没有思路呀？

**Comment by naiba** [comment]
没有遇到过哈，故障也不是100%失败，低于一定可用率就会显示故障。

cmd/playground 有代码可以临时调试

**Comment by naiba** [comment]
还有你输入框里输入的值是 `8.8.8.8`，类型选的 ICMP 吗

**Comment by naiba** [comment]
https://ops.naibahq.com/service 运行良好哦

**Comment by maker2002** [comment]
> 没有遇到过哈，故障也不是100%失败，低于一定可用率就会显示故障。
> 
> cmd/playground 有代码可以临时调试

我在2台debian的系统上安装后添加服务监控均是无数据的状态...
关于cmd/playground的调试有没有更多使用说明呀？
