### ISSUE TITLE
实时通道断开

### ISSUE THREAD

**Issue by simplove** [naiba/nezha#13]
实时通道断开
无法实时获取最新监控数据咯

用：8080的网址就显示实时通道建立 没问题
换到HTTPS会有这个提示
宝塔做的反代
这个咱解决，老大

**Comment by naiba** [comment]
再看看README

**Comment by simplove** [comment]
在站点修改--配置文件找到以下代码
#server_name stasut.yoursite.com
在下面插入：
    location /ws {
        proxy_pass http://ip:站点访问端口;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }
把上面的IP换成自己的IP和端口号。


感谢
