### ISSUE TITLE
流量统计

### ISSUE THREAD

**Issue by qd201211** [naiba/nezha#15]
发现现在流量统计存在重启后重置为0的问题，有时服务器意外停机后就无法对使用流量进行参考。
是否可以修改一下这个流量统计，可以让它在重启后依旧可以显示流量用量。（知道一个vnstat可以做到，不知能不能改）谢谢大佬了！

**Comment by naiba** [comment]
流量只是简单读取的系统信息，系统重启重置那就重置，且每个人流量统计周期可能不一致，不会实现，如果你有想法，欢迎PR
