### ISSUE TITLE
错误信息：Post "https://github.com/login/oauth/access_token

### ISSUE THREAD

**Issue by tmmtoo** [naiba/nezha#17]
错误信息：Post "https://github.com/login/oauth/access_token": dial tcp: lookup github.com on 127.0.0.11:53: read udp 127.0.0.1:40397->127.0.0.11:53: i/o timeout

<img width="339" alt="Snipaste_2020-12-10_08-58-50" src="https://user-images.githubusercontent.com/62988099/101707393-17abc200-3ac6-11eb-8e1a-5829f4c9d7af.png">

**Comment by naiba** [comment]
服务器请求GitHub有问题，尝试修改一下DNS服务器 `/etc/resolv.conf` 多登录几次，面板最好还是放到海外服务器。
