### ISSUE TITLE
大佬支持下GPU不?

### ISSUE THREAD

**Issue by HuJK** [naiba/nezha#20]
我朋友寫了一個探針，用來幫實驗室同學查看哪台GPU可用，上去跑訓練
https://github.com/HuJK/servstat

大老有計畫支持下gpu，可以看使用率+使用者嗎?

**Comment by naiba** [comment]
1. 需求较小众
2. 本人没有灵感解决GPU需求与当前UI的融入，可以让你朋友来提一下PR

**Comment by naiba** [comment]
看你们那个监控还有按用户展示，能不能抽取出来一个比较通用且你们够用GPU需求，还要考虑多显卡情况，重新开一个issue

**Comment by HuJK** [comment]
確實...

我們實驗室的使用情境是多用戶多主機，每個用戶可以看那些資源被誰占用
用戶可以連上有空閒顯卡資源的主機，或是直接找人商議
和一般mjj們的情境不太一樣(單用戶多主機)

我原本想在我朋友的探針上加上硬碟空間/網路流量/CPU溫度/顯卡溫度/UpTime之類的功能的。突然想到這不就是探針的基本功能嗎？不用重複造輪子

不過確實使用情境不一樣，合併成一個專案不一定方便，感謝大佬的回覆
