### ISSUE TITLE
节点框架可以自定义吗？

### ISSUE THREAD

**Issue by frankhanson1230** [naiba/nezha#27]
节点框架可以自定义吗？有点小 有一些显示不出来

**Comment by naiba** [comment]
截个图看一下

**Comment by frankhanson1230** [comment]
> 截个图看一下

额哥们 可能是我放在法国 ovh  有点慢 没刷新出来 ，更新的时候 可以把流量统计 加上吗 这样我才知道 那个服务器我用了多少流量 谢谢。。
