### ISSUE TITLE
能否增加节点显示排序功能(作者说满20赞就加,靠各位大佬了)

### ISSUE THREAD

**Issue by Moexin** [naiba/nezha#29]
能否增加节点显示排序功能，强迫症刚需

**Comment by naiba** [comment]
描述清楚

**Comment by Moexin** [comment]
默认是按照节点ID顺序显示的。例如我添加了三个节点，ID分别为1，2，3。可我想在首页上以节点ID分别为2，3，1的顺序显示。

**Comment by naiba** [comment]
拉人点赞，满 20 加排序

**Comment by zhucaidan** [comment]
也希望删掉节点的时候连ID一起删了，这样添加下一个节点就不会跳过刚刚那个ID数字

**Comment by Es-dese** [comment]
> 能否增加节点显示排序功能，强迫症刚需

是啊，顺便加上服务器分组功能那肯定更好
