### ISSUE TITLE
大佬启动提示这个,是什么问题?

### ISSUE THREAD

**Issue by steadshy** [naiba/nezha#3]
Pulling dashboard (docker.pkg.github.com/p14yground/nezha/dashboard:)...
ERROR: Get https://docker.pkg.github.com/v2/p14yground/nezha/dashboard/manifests/latest: no basic auth credentials

**Comment by naiba** [comment]
执行一下 docker login docker.pkg.github.comgithub的镜像需要登录才能拉

**Comment by naiba** [comment]
现在最新的 `docker-compose.yaml` 可以匿名拉镜像了 不需要登录

**Comment by steadshy** [comment]
大佬，为什么docker-compose up -d启动后 ip+端口无法访问面板，纯小白，很想用这个探针。

**Comment by naiba** [comment]
IP:8008  默认是给反代用的，不推荐直接绑定到80
