### ISSUE TITLE
希望增加面板的自定义分组功能

### ISSUE THREAD

**Issue by Es-dese** [naiba/nezha#32]
希望增加面板主页，左上角的自定义分组功能

例如按国家、用途分类，自定义昵称分类等等。。

如图：
![20201222184212](https://user-images.githubusercontent.com/71542548/102953131-73425c00-4485-11eb-8685-98e4aa455247.png)

**Comment by zhucaidan** [comment]
同求，分页貌似不错，都堆在首页有时候太多了；有时候首页的节点莫名其妙显示掉线刷新一下又好了不知道是什么问题？

**Comment by naiba** [comment]
20赞也不能加了，这个短期不会做。有希望加入的前端欢迎联系。
