### ISSUE TITLE
新版本进度条低于一定百分比只显示符号问题

### ISSUE THREAD

**Issue by Es-dese** [naiba/nezha#38]
新版本的监控进度条，在低于一定百分比（目测<10%）的时候只会显示%符号，旧版无此问题
新版：
![20201225123118](https://user-images.githubusercontent.com/71542548/103141736-6f911e00-46ad-11eb-957c-2573b2036543.png)
旧版：
![20201225123137](https://user-images.githubusercontent.com/71542548/103141738-74ee6880-46ad-11eb-9f67-42c8eb503a03.png)
希望能修复一下进度条的显示，让例如1%也可以正确的显示出数字；
另外可以的话“在线时间”处的详细信息，可否有方法改为旧版的精确到秒而不只是显示天数？

**Comment by naiba** [comment]
最后一个commit已经优化
