### ISSUE TITLE
访问受限      错误信息：该用户不是本站点管理员，无法登录

### ISSUE THREAD

**Issue by RoseannePark1** [naiba/nezha#39]
在安装好面板后，进入面板，进行登陆，就显示这个，这是一个新号，之前的号被锁定无法使用

以下是面板日志

Attaching to dashboard_dashboard_1
dashboard_1  | 
dashboard_1  | 2020/12/26 07:27:39 /go/pkg/mod/gorm.io/driver/sqlite@v1.1.4/migrator.go:32
dashboard_1  | [0.089ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type='table' AND name="servers"
dashboard_1  | 
dashboard_1  | 2020/12/26 07:27:39 /dashboard/cmd/dashboard/main.go:38
dashboard_1  | [2.680ms] [rows:0] CREATE TABLE `servers` (`id` integer,`created_at` datetime,`updated_at` datetime,`deleted_at` datetime,`name` text,`secret` text,`last_active` datetime,PRIMARY KEY (`id`))
dashboard_1  | 
dashboard_1  | 2020/12/26 07:27:39 /go/pkg/mod/gorm.io/driver/sqlite@v1.1.4/migrator.go:32
dashboard_1  | [0.063ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type='table' AND name="users"
dashboard_1  | 
dashboard_1  | 2020/12/26 07:27:39 /dashboard/cmd/dashboard/main.go:38
dashboard_1  | [3.595ms] [rows:0] CREATE TABLE `users` (`id` integer,`created_at` datetime,`updated_at` datetime,`deleted_at` datetime,`login` text,`avatar_url` text,`name` text,`blog` text,`email` text,`hireable` numeric,`bio` text,`token` text,`token_expired` datetime,`super_admin` numeric,PRIMARY KEY (`id`))
dashboard_1  | 
dashboard_1  | 2020/12/26 07:27:39 /go/pkg/mod/gorm.io/driver/sqlite@v1.1.4/migrator.go:32
dashboard_1  | [0.050ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type='table' AND name="notifications"
dashboard_1  | 
dashboard_1  | 2020/12/26 07:27:39 /dashboard/cmd/dashboard/main.go:38
dashboard_1  | [3.199ms] [rows:0] CREATE TABLE `notifications` (`id` integer,`created_at` datetime,`updated_at` datetime,`deleted_at` datetime,`name` text,`url` text,`request_method` integer,`request_type` integer,`request_body` longtext,`verify_ssl` numeric,PRIMARY KEY (`id`))
dashboard_1  | 
dashboard_1  | 2020/12/26 07:27:39 /go/pkg/mod/gorm.io/driver/sqlite@v1.1.4/migrator.go:32
dashboard_1  | [0.141ms] [rows:-] SELECT count(*) FROM sqlite_master WHERE type='table' AND name="alert_rules"
dashboard_1  | 
dashboard_1  | 2020/12/26 07:27:39 /dashboard/cmd/dashboard/main.go:38
dashboard_1  | [2.772ms] [rows:0] CREATE TABLE `alert_rules` (`id` integer,`created_at` datetime,`updated_at` datetime,`deleted_at` datetime,`name` text,`rules_raw` text,`enable` numeric,PRIMARY KEY (`id`))
dashboard_1  | 
dashboard_1  | 2020/12/26 07:27:39 /dashboard/cmd/dashboard/main.go:41
dashboard_1  | [0.236ms] [rows:0] SELECT * FROM `servers`
dashboard_1  | [GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.
dashboard_1  | 
dashboard_1  | [GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
dashboard_1  |  - using env:	export GIN_MODE=release
dashboard_1  |  - using code:	gin.SetMode(gin.ReleaseMode)
dashboard_1  | 
dashboard_1  | [GIN-debug] GET    /static/*filepath         --> github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (4 handlers)
dashboard_1  | [GIN-debug] HEAD   /static/*filepath         --> github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (4 handlers)
dashboard_1  | 
dashboard_1  | 2020/12/26 07:27:39 /dashboard/service/alertmanager/alertmanager.go:34
dashboard_1  | [0.586ms] [rows:0] SELECT * FROM `notifications`
dashboard_1  | 
dashboard_1  | 2020/12/26 07:27:39 /dashboard/service/alertmanager/alertmanager.go:39
dashboard_1  | [0.174ms] [rows:0] SELECT * FROM `alert_rules`
dashboard_1  | [GIN-debug] Loaded HTML Templates (27): 
dashboard_1  | 	- confirm.html
dashboard_1  | 	- setting.html
dashboard_1  | 	- 
dashboard_1  | 	- footer.html
dashboard_1  | 	- common/footer
dashboard_1  | 	- component/confirm
dashboard_1  | 	- home.html
dashboard_1  | 	- menu.html
dashboard_1  | 	- dashboard/notification
dashboard_1  | 	- dashboard/setting
dashboard_1  | 	- dashboard/error
dashboard_1  | 	- dashboard/server
dashboard_1  | 	- common/header
dashboard_1  | 	- component/server
dashboard_1  | 	- common/menu
dashboard_1  | 	- login.html
dashboard_1  | 	- header.html
dashboard_1  | 	- error.html
dashboard_1  | 	- theme-hotaru/home
dashboard_1  | 	- component/rule
dashboard_1  | 	- dashboard/login
dashboard_1  | 	- README.md
dashboard_1  | 	- theme-default/home
dashboard_1  | 	- notification.html
dashboard_1  | 	- component/notification
dashboard_1  | 	- rule.html
dashboard_1  | 	- server.html
dashboard_1  | 
dashboard_1  | [GIN-debug] GET    /                         --> github.com/naiba/nezha/cmd/dashboard/controller.(*commonPage).home-fm (5 handlers)
dashboard_1  | [GIN-debug] GET    /ws                       --> github.com/naiba/nezha/cmd/dashboard/controller.(*commonPage).ws-fm (5 handlers)
dashboard_1  | [GIN-debug] GET    /login                    --> github.com/naiba/nezha/cmd/dashboard/controller.(*guestPage).login-fm (5 handlers)
dashboard_1  | [GIN-debug] GET    /oauth2/login             --> github.com/naiba/nezha/cmd/dashboard/controller.(*oauth2controller).login-fm (5 handlers)
dashboard_1  | [GIN-debug] GET    /oauth2/callback          --> github.com/naiba/nezha/cmd/dashboard/controller.(*oauth2controller).callback-fm (5 handlers)
dashboard_1  | [GIN-debug] GET    /server                   --> github.com/naiba/nezha/cmd/dashboard/controller.(*memberPage).server-fm (5 handlers)
dashboard_1  | [GIN-debug] GET    /notification             --> github.com/naiba/nezha/cmd/dashboard/controller.(*memberPage).notification-fm (5 handlers)
dashboard_1  | [GIN-debug] GET    /setting                  --> github.com/naiba/nezha/cmd/dashboard/controller.(*memberPage).setting-fm (5 handlers)
dashboard_1  | [GIN-debug] POST   /api/logout               --> github.com/naiba/nezha/cmd/dashboard/controller.(*memberAPI).logout-fm (5 handlers)
dashboard_1  | [GIN-debug] POST   /api/server               --> github.com/naiba/nezha/cmd/dashboard/controller.(*memberAPI).addOrEditServer-fm (5 handlers)
dashboard_1  | [GIN-debug] POST   /api/notification         --> github.com/naiba/nezha/cmd/dashboard/controller.(*memberAPI).addOrEditNotification-fm (5 handlers)
dashboard_1  | [GIN-debug] POST   /api/alert-rule           --> github.com/naiba/nezha/cmd/dashboard/controller.(*memberAPI).addOrEditAlertRule-fm (5 handlers)
dashboard_1  | [GIN-debug] POST   /api/setting              --> github.com/naiba/nezha/cmd/dashboard/controller.(*memberAPI).updateSetting-fm (5 handlers)
dashboard_1  | [GIN-debug] DELETE /api/:model/:id           --> github.com/naiba/nezha/cmd/dashboard/controller.(*memberAPI).delete-fm (5 handlers)
dashboard_1  | [GIN-debug] Listening and serving HTTP on :80
dashboard_1  | 
dashboard_1  | 2020/12/26 07:27:51 /dashboard/pkg/mygin/auth.go:45 record not found
dashboard_1  | [0.434ms] [rows:0] SELECT * FROM `users` WHERE token = "" ORDER BY `users`.`id` LIMIT 1
dashboard_1  | [GIN] 2020/12/26 - 07:27:51 | 200 |   13.243851ms |   39.161.242.53 | GET      "/"
dashboard_1  | 
dashboard_1  | 2020/12/26 07:27:52 /dashboard/pkg/mygin/auth.go:45 record not found
dashboard_1  | [0.409ms] [rows:0] SELECT * FROM `users` WHERE token = "" ORDER BY `users`.`id` LIMIT 1
dashboard_1  | 
dashboard_1  | 2020/12/26 07:27:54 /dashboard/pkg/mygin/auth.go:45 record not found
dashboard_1  | [0.433ms] [rows:0] SELECT * FROM `users` WHERE token = "" ORDER BY `users`.`id` LIMIT 1
dashboard_1  | [GIN] 2020/12/26 - 07:27:54 | 200 |    4.216838ms |   39.161.242.53 | GET      "/login"
dashboard_1  | 
dashboard_1  | 2020/12/26 07:27:55 /dashboard/pkg/mygin/auth.go:45 record not found
dashboard_1  | [0.346ms] [rows:0] SELECT * FROM `users` WHERE token = "" ORDER BY `users`.`id` LIMIT 1
dashboard_1  | [GIN] 2020/12/26 - 07:27:55 | 302 |      928.84?s |   39.161.242.53 | GET      "/oauth2/login"
dashboard_1  | [GIN] 2020/12/26 - 07:27:56 | 200 |  4.002382672s |   39.161.242.53 | GET      "/ws"
dashboard_1  | 
dashboard_1  | 2020/12/26 07:30:13 /dashboard/pkg/mygin/auth.go:45 record not found
dashboard_1  | [0.532ms] [rows:0] SELECT * FROM `users` WHERE token = "" ORDER BY `users`.`id` LIMIT 1
dashboard_1  | [GIN] 2020/12/26 - 07:30:13 | 200 |    6.154416ms |   39.161.242.53 | GET      "/"
dashboard_1  | 
dashboard_1  | 2020/12/26 07:30:14 /dashboard/pkg/mygin/auth.go:45 record not found
dashboard_1  | [0.357ms] [rows:0] SELECT * FROM `users` WHERE token = "" ORDER BY `users`.`id` LIMIT 1
dashboard_1  | 
dashboard_1  | 2020/12/26 07:30:15 /dashboard/pkg/mygin/auth.go:45 record not found
dashboard_1  | [0.565ms] [rows:0] SELECT * FROM `users` WHERE token = "" ORDER BY `users`.`id` LIMIT 1
dashboard_1  | [GIN] 2020/12/26 - 07:30:15 | 200 |    6.032138ms |   39.161.242.53 | GET      "/login"
dashboard_1  | 
dashboard_1  | 2020/12/26 07:30:16 /dashboard/pkg/mygin/auth.go:45 record not found
dashboard_1  | [0.425ms] [rows:0] SELECT * FROM `users` WHERE token = "" ORDER BY `users`.`id` LIMIT 1
dashboard_1  | [GIN] 2020/12/26 - 07:30:16 | 302 |     731.095?s |   39.161.242.53 | GET      "/oauth2/login"
dashboard_1  | [GIN] 2020/12/26 - 07:30:18 | 200 |  4.005640777s |   39.161.242.53 | GET      "/ws"
dashboard_1  | 
dashboard_1  | 2020/12/26 07:30:32 /dashboard/pkg/mygin/auth.go:45 record not found
dashboard_1  | [0.713ms] [rows:0] SELECT * FROM `users` WHERE token = "" ORDER BY `users`.`id` LIMIT 1
dashboard_1  | [GIN] 2020/12/26 - 07:30:33 | 200 |  730.568771ms |   39.161.242.53 | GET      "/oauth2/callback?code=22d2726b6717a131e8a8&state=qHBFzF"
dashboard_1  | 
dashboard_1  | 2020/12/26 07:31:01 /dashboard/pkg/mygin/auth.go:45 record not found
dashboard_1  | [0.404ms] [rows:0] SELECT * FROM `users` WHERE token = "" ORDER BY `users`.`id` LIMIT 1
dashboard_1  | [GIN] 2020/12/26 - 07:31:02 | 200 |  672.373251ms |   39.161.242.53 | GET      "/oauth2/callback?code=fd634ae0d6ba1f05dbd9&state=qHBFzF"
dashboard_1  | 
dashboard_1  | 2020/12/26 07:31:48 /dashboard/pkg/mygin/auth.go:45 record not found
dashboard_1  | [0.442ms] [rows:0] SELECT * FROM `users` WHERE token = "" ORDER BY `users`.`id` LIMIT 1
dashboard_1  | [GIN] 2020/12/26 - 07:31:48 | 200 |    7.544068ms |   39.161.242.53 | GET      "/"
dashboard_1  | 
dashboard_1  | 2020/12/26 07:31:49 /dashboard/pkg/mygin/auth.go:45 record not found
dashboard_1  | [0.425ms] [rows:0] SELECT * FROM `users` WHERE token = "" ORDER BY `users`.`id` LIMIT 1
dashboard_1  | 
dashboard_1  | 2020/12/26 07:31:50 /dashboard/pkg/mygin/auth.go:45 record not found
dashboard_1  | [0.380ms] [rows:0] SELECT * FROM `users` WHERE token = "" ORDER BY `users`.`id` LIMIT 1
dashboard_1  | [GIN] 2020/12/26 - 07:31:50 | 200 |     4.61317ms |   39.161.242.53 | GET      "/login"
dashboard_1  | 
dashboard_1  | 2020/12/26 07:31:52 /dashboard/pkg/mygin/auth.go:45 record not found
dashboard_1  | [0.359ms] [rows:0] SELECT * FROM `users` WHERE token = "" ORDER BY `users`.`id` LIMIT 1
dashboard_1  | [GIN] 2020/12/26 - 07:31:52 | 302 |    1.090459ms |   39.161.242.53 | GET      "/oauth2/login"
dashboard_1  | [GIN] 2020/12/26 - 07:31:53 | 200 |  4.001898342s |   39.161.242.53 | GET      "/ws"
dashboard_1  | 
dashboard_1  | 2020/12/26 07:31:59 /dashboard/pkg/mygin/auth.go:45 record not found
dashboard_1  | [0.399ms] [rows:0] SELECT * FROM `users` WHERE token = "" ORDER BY `users`.`id` LIMIT 1
dashboard_1  | [GIN] 2020/12/26 - 07:32:00 | 200 |  650.492538ms |   39.161.242.53 | GET      "/oauth2/callback?code=5b4b3e6d6432f0e0940f&state=QZPyKW"
dashboard_1  | 
dashboard_1  | 2020/12/26 07:39:10 /dashboard/pkg/mygin/auth.go:45 record not found
dashboard_1  | [0.329ms] [rows:0] SELECT * FROM `users` WHERE token = "" ORDER BY `users`.`id` LIMIT 1
dashboard_1  | [GIN] 2020/12/26 - 07:39:10 | 200 |    3.949433ms |   39.161.242.53 | GET      "/oauth2/callback"
dashboard_1  | 
dashboard_1  | 2020/12/26 07:39:22 /dashboard/pkg/mygin/auth.go:45 record not found
dashboard_1  | [0.596ms] [rows:0] SELECT * FROM `users` WHERE token = "" ORDER BY `users`.`id` LIMIT 1
dashboard_1  | [GIN] 2020/12/26 - 07:39:22 | 200 |    5.966571ms |   39.161.242.53 | GET      "/"
dashboard_1  | 
dashboard_1  | 2020/12/26 07:39:23 /dashboard/pkg/mygin/auth.go:45 record not found
dashboard_1  | [0.771ms] [rows:0] SELECT * FROM `users` WHERE token = "" ORDER BY `users`.`id` LIMIT 1
dashboard_1  | 
dashboard_1  | 2020/12/26 07:39:25 /dashboard/pkg/mygin/auth.go:45 record not found
dashboard_1  | [0.430ms] [rows:0] SELECT * FROM `users` WHERE token = "" ORDER BY `users`.`id` LIMIT 1
dashboard_1  | [GIN] 2020/12/26 - 07:39:25 | 200 |    5.908021ms |   39.161.242.53 | GET      "/login"
dashboard_1  | 
dashboard_1  | 2020/12/26 07:39:27 /dashboard/pkg/mygin/auth.go:45 record not found
dashboard_1  | [0.593ms] [rows:0] SELECT * FROM `users` WHERE token = "" ORDER BY `users`.`id` LIMIT 1
dashboard_1  | [GIN] 2020/12/26 - 07:39:27 | 302 |    1.094523ms |   39.161.242.53 | GET      "/oauth2/login"
dashboard_1  | [GIN] 2020/12/26 - 07:39:27 | 200 |  4.002917702s |   39.161.242.53 | GET      "/ws"
dashboard_1  | 
dashboard_1  | 2020/12/26 07:39:27 /dashboard/pkg/mygin/auth.go:45 record not found
dashboard_1  | [0.538ms] [rows:0] SELECT * FROM `users` WHERE token = "" ORDER BY `users`.`id` LIMIT 1
dashboard_1  | [GIN] 2020/12/26 - 07:39:28 | 200 |  521.763471ms |   39.161.242.53 | GET      "/oauth2/callback?code=61496aff4b544d72471c&state=6x3yyB"

**Comment by naiba** [comment]
更新面板配置就行了

**Comment by RoseannePark1** [comment]
> 更新面板配置就行了

> 重启并更新面板
Pulling dashboard ... done
Stopping dashboard_dashboard_1 ... done
Removing dashboard_dashboard_1 ... done
Removing network dashboard_default
Creating network "dashboard_default" with the default driver
Creating dashboard_dashboard_1 ... done
哪吒面板 重启成功
默认管理面板地址：域名:站点访问端口
更新后也还是登陆失败

**Comment by RoseannePark1** [comment]
> 更新面板配置就行了

脑子抽到了，id打错了，获得的数字id也是错的
