### ISSUE TITLE
希望增加非docker部署方式/希望更新示例config.yaml

### ISSUE THREAD

**Issue by shzxm** [naiba/nezha#41]
希望增加非docker部署方式

希望在本地部署nezha 非docker部署的方式
虽然找到了相关的教程 但是示例配置文件缺少参数 
https://www.zhujizixun.com/2843.html

希望更新示例config.yaml
示例文件 缺少自定义nz rpc port

**Comment by naiba** [comment]
30赞加非Docker一键脚本

**Comment by Whichbfj28** [comment]
300赞加非Docker部署方式。

**Comment by shzxm** [comment]
> 30赞加非Docker一键脚本

啊.就是...其实只要更新 config.yaml  就好了......先更新example config.yaml.

那我也点个赞
