### ISSUE TITLE
更新v0.20.9导致无法启动，如何处置？

### ISSUE THREAD

**Issue by webhawk1234** [naiba/nezha#469]
错误日志：
-- The job identifier is 1532 and the job result is done.
Nov 06 00:32:55 44a891518d systemd[1]: nezha-dashboard.service: Start request repeated too quickly.
Nov 06 00:32:55 44a891518d systemd[1]: nezha-dashboard.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- The unit nezha-dashboard.service has entered the 'failed' state with result 'exit-code'.
Nov 06 00:32:55 44a891518d systemd[1]: Failed to start Nezha Dashboard.
-- Subject: A start job for unit nezha-dashboard.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- A start job for unit nezha-dashboard.service has finished with a failure.
-- 
-- The job identifier is 1532 and the job result is failed.

**Comment by FreeyW** [comment]
遇到了相同的问题

**Comment by emengweb** [comment]
同样无法启动，求修复

**Comment by Smart-Kevin** [comment]
The same error.
