### ISSUE TITLE
通知失效了

### ISSUE THREAD

**Issue by zkysimon** [naiba/nezha#48]
自建的tg机器人，https://github.com/pupilcc/pushbot
之前都是可以正常通知的（和server酱一样的填法填在后台的），自从前两天更新了之后，就没收到过通知了，机器人没问题，试过了可以通知。

**Comment by naiba** [comment]
写法有变，再研究研究最新 README（也不发你现在配置

**Comment by naiba** [comment]
更新一下面板，上个版本可能存在问题，最新的打了些日志，如果收不到可以发日志
