### ISSUE TITLE
流量统计不准（网卡问题）

### ISSUE THREAD

**Issue by Noahsarker** [naiba/nezha#49]
应该是机机安装了docker，看监控 网速直接翻了三倍-五倍。看看怎么安排下过滤这些网卡 （或其他虚拟网卡），或者做成配置中可自定义网卡

**Comment by naiba** [comment]
有时间会做成自选硬盘分区、网卡

**Comment by huaxing211** [comment]
确实，如果已经安装了docker应用，使用这个的话，流量统计都是不准的，内存也不准了！

查询网卡流量：
eth0:RX packets 51787355  bytes 4775024610 (4.4 GiB)
        TX packets 1201834  bytes 712485519 (679.4 MiB)
面板中显示：↓6GB，↑2GB

内存实际1.6GB，面板显示1GB.

**Comment by naiba** [comment]
没人碰到这个问题，可以加群把你机器详细信息反馈一下，先关闭了。
