### ISSUE TITLE
WebSocket握手报错

### ISSUE THREAD

**Issue by ikxin** [naiba/nezha#5]
提示实时通道断开，无法实时获取最新监控数据咯

控制台信息：
`WebSocket connection to 'wss://status.ikxin.com/ws' failed: Error during WebSocket handshake: Unexpected response code: 400`

**Comment by naiba** [comment]
你用的什么反代，需要反代支持ws，

比如使用 caddy1 的话需要配置 proxy { websocket }

**Comment by ikxin** [comment]
你好，我用的是nginx，能否请教一下如何反代ws

另外，我在用一键脚本搭建好面板的时候，使用github登录提示

错误信息：Post "https://github.com/login/oauth/access_token": dial tcp: lookup github.com on 127.0.0.11:53: read udp 127.0.0.1:46997->127.0.0.11:53: i/o timeout

**Comment by naiba** [comment]
查看 README 试试

**Comment by ikxin** [comment]
谢谢作者，ws的问题解决了，还想请问下登陆的时候提示

```
错误信息：Post "https://github.com/login/oauth/access_token": dial tcp: lookup github.com on 127.0.0.11:53: read udp 127.0.0.1:46997->127.0.0.11:53: i/o timeout
```

是什么引起的

**Comment by naiba** [comment]
docker 容器 dns 解析有点问题，本机dns超时 lookup github.com on 127.0.0.11:53
尝试修改DNS / 重启 docker

**Comment by ikxin** [comment]
你好，我尝试了在hosts指定github.com的地址、在docker-compose.yaml添加dns和其他各种方法，结果还是报一样的错误，想问下如何解决？

**Comment by naiba** [comment]
先将agnet重启，会自动升级到最新版，1.9 版本之前的有点问题

`docker dial tcp lookup no such host` 这个问题我也没遇到过，多搜索一下试试
