### ISSUE TITLE
收不到通知

### ISSUE THREAD

**Issue by zkysimon** [naiba/nezha#50]
![(UK)EME{QQI$9@2A2BI{)JY](https://user-images.githubusercontent.com/61656204/103729269-08fbf080-501b-11eb-9319-f27b93112e57.png)
之前可以收到的，后来更新之后不管怎么改都收不到通知了

**Comment by naiba** [comment]
保存的时候测试通知收不到吗

**Comment by naiba** [comment]
再更新一下

**Comment by zkysimon** [comment]
更新之后收到了
