### ISSUE TITLE
消息通知的方式能不能增加 telegram ?

### ISSUE THREAD

**Issue by haitau** [naiba/nezha#51]
https://api.telegram.org/bot012345678:xxxxxxxxxxxxxxxxx-xxxxxxxxxx-xxxxxx/sendMessage?chat_id=@XXXXXX&text=#NEZHA#

类似这样，面板用户自己去建一个机器人，用机器人给自己 telegram 账号发消息？

**Comment by naiba** [comment]
是的

**Comment by haitau** [comment]
> 是的

文档能不加一下这个配置的说明，自己折腾半天还是报错，加不了。

**Comment by naiba** [comment]
不用tg，到论坛问问吧

**Comment by haitau** [comment]
晕，被网上文章误导了，chat_id=xxxxxxx ，查 telegram 原始 api，不要加@

**Comment by naiba** [comment]
可以提交一个PR放到README吗

**Comment by haitau** [comment]
我试试

**Comment by haitau** [comment]
不能提交 pr ，我写了一下，看看有谁能加进去吧

 - telegram示例
      - 备注：telegram机器人消息通知
      - URL：https://api.telegram.org/botXXXXXX/sendMessage?chat_id=YYYYYY&text=#NEZHA#
      - 请求方式: GET
      - 请求类型: 默认
      - Body: 空
      - URL参数获取说明：
           botXXXXXX 中的 XXXXXX 是在 telegram中关注官方 @BotFather ，输入/newbot ，创建新的机器人（bot）时，
           会提供的 token（在提示Use this token to access the HTTP API:后面一行）
           这里 'bot' 三个字母不可少。
           创建 bot 后，需要先在 telegram中与BOT进行对话（随便发个消息），然后才可用 API发送消息。
           YYYYYY 是 telegram 用户的数字 ID。与机器人@userinfobot 对话可获得。
