### ISSUE TITLE
删除未停agent，面板就崩

### ISSUE THREAD

**Issue by seav1** [naiba/nezha#539]
### 运行环境

面板：nginx:alpine，Agent，不管什么系统，面板崩后都不会再上报IP

### Agent 版本

v1.0.2

### 描述问题

<details></details>
不小心删到没停的agnet，面板就崩，现有的所有agent只要不重启。就不会上报IP地址。一旦操作错。就必须重启所有Agent

### 复现步骤

<details></details>
不小心删到没停的agnet，面板就崩，现有的所有agent只要不重启。就不会上报IP地址。一旦操作错。就必须重启所有Agent
![微信图片_20241202155300](https://github.com/user-attachments/assets/cb96ba54-0fb4-4da3-a789-82d699664bab)

### 附加信息

<details></details>

### 验证

- [X] 我确认这是一个 nezha (哪吒面板) 的问题。
- [X] 我已经搜索了 Issues，并确认该问题之前没有被反馈过。

**Comment by uubulb** [comment]
请附带您的崩溃日志
内部开发的时候遇过类似问题
