### ISSUE TITLE
请问宝塔面板可以安装吗？

### ISSUE THREAD

**Issue by xiaomcm** [naiba/nezha#6]
开发者你好，我的服务器全是宝塔面板。请问可以安装吗？可以直接通过宝塔部署站点吗？

**Comment by naiba** [comment]
可以与宝塔共存，安装后使用宝塔反代一下即可。

**Comment by xiaomcm** [comment]
还有一个问题，一键脚本在centos7上面执行没有任何反应

**Comment by naiba** [comment]
还在测试，等WIP移除后可用

**Comment by naiba** [comment]
一键脚本可以使用了

**Comment by xiaomcm** [comment]
我试试

**Comment by xiaomcm** [comment]
sudo: nezha.sh: command not found

sudo nezha.sh 改为：sudo bash nezha.sh

不改会无法执行

**Comment by naiba** [comment]
宝塔反代配置在 README 有说明了
