### ISSUE TITLE
IP变动提醒有问题

### ISSUE THREAD

**Issue by haitau** [naiba/nezha#62]
几台机子都有IPv4和IPv6，nezha更新后，IP是没变动的，但不停收到IP变动通知。
例如：
服务器：German euserv IP变更提醒，旧IP：2a02:180:6:1::34aa，新IP：ip(v4: 2a02:180:6:1::34aa, v6: 2a02:180:6:1::34aa
)。

**Comment by naiba** [comment]
通知完就好了，不会一直通知
