### ISSUE TITLE
0.2.2 版本新增的“服务状态”内条目删除报错等

### ISSUE THREAD

**Issue by zhucaidan** [naiba/nezha#63]
刚刚更新的0.2.2 版本，新增的“服务状态”功能添加条目后有以下三个错误：

1、ICMP Ping无效，添加后会提示故障，实际主机SSH可以ping通这个IP
2、HTTP-GET条目，无法正确支持http协议，而https检测正常
3、当已创建的条目删除后，再打开前台的“服务状态”界面，会提示“HTTP ERROR 500”错误，
必须把刚刚删除的条目添加回去，“服务状态”界面才可以恢复正常显示

**Comment by naiba** [comment]
更新一下面板再试一下

**Comment by zhucaidan** [comment]
删除条目和重新添加不会500错误了，
但是新添加的也不知道有没有开始工作，等了很久还是“无数据”
请问下大概多久会开始收集数据？间隔多久会再次显示呢

**Comment by naiba** [comment]
10分钟左右

**Comment by zhucaidan** [comment]
等了一会，ping 1.1.1.1和8.8.8.8还是故障，HTTP的监控良好，但是ping和http监控延迟为0ms
