### ISSUE TITLE
2.0 执行脚本更新的时候报错

### ISSUE THREAD

**Issue by haitau** [naiba/nezha#64]
5.  重启并更新面板
    6.  查看面板日志
    7.  卸载管理面板
    ————————————————-
    8.  安装监控Agent
    9.  修改Agent配置
    10. 卸载Agent
    11. 重启Agent

请输入选择 [0-11]: 5
> 重启并更新面板
./nezha.sh: line 298: cd: /opt/nezha/dashboard: No such file or directory
./nezha.sh: line 299: docker-compose: command not found
./nezha.sh: line 300: docker-compose: command not found
./nezha.sh: line 301: docker-compose: command not found
重启失败，可能是因为启动时间超过了两秒，请稍后查看日志信息

**Comment by naiba** [comment]
你这docker都找不到了，先解决这个问题。

解决不了直接完全重装得了

**Comment by haitau** [comment]
直接重装了。
