### ISSUE TITLE
0.2.x版本前端显示问题

### ISSUE THREAD

**Issue by peng4740** [naiba/nezha#66]
显示缩放设置为200%(或高于200%)的时候文字会重叠在一起(我电脑默认就是200%)，0.1.x版本的时候没这个问题。  

如图：  

![200%缩放](https://developer-forum-online.cdn.bcebos.com/a526ba8a-11a2-4647-8d55-2892302b01d2.jpg)  
[https://developer-forum-online.cdn.bcebos.com/a526ba8a-11a2-4647-8d55-2892302b01d2.jpg](https://developer-forum-online.cdn.bcebos.com/a526ba8a-11a2-4647-8d55-2892302b01d2.jpg)  
  
  
![150%缩放](https://developer-forum-online.cdn.bcebos.com/852de630-5a1d-4de5-93d7-671457cbcf64.jpg)  
[https://developer-forum-online.cdn.bcebos.com/852de630-5a1d-4de5-93d7-671457cbcf64.jpg](https://developer-forum-online.cdn.bcebos.com/852de630-5a1d-4de5-93d7-671457cbcf64.jpg)

**Comment by naiba** [comment]
欢迎有兴趣的工程师一起优化体验
