### ISSUE TITLE
刚刚更新最新版本，ICMP的ping第一次测试以后不通

### ISSUE THREAD

**Issue by zhucaidan** [naiba/nezha#68]
如图所示分别添加了CF的DNS ICMP：1.1.1.1
第二个为谷歌DNS TCP：8.8.8.8:53

ICMP在第一次ping通以后，之后都不再可以ping通 (第一次通的情况下也不会显示延迟，为0ms)
TCP的ping+端口一切正常

![20210117154432](https://user-images.githubusercontent.com/47970938/104859584-4bef7b00-58db-11eb-8f99-c5f49db9dbbb.png)

**Comment by maker2002** [comment]
请问你解决了这个问题吗？我刚刚安装好，也是出现icmp ping监控0ms，然后就一直不通了。
