### ISSUE TITLE
更新了之后websocket一直断开 #help

### ISSUE THREAD

**Issue by Antake2333** [naiba/nezha#69]
操作了很久但是websocket一直断开，在docker中有个memory panic

**Comment by naiba** [comment]
操作了很久是什么意思？

memory panic 那个日志复制过来看看

**Comment by Antake2333** [comment]
就是重装了 也反复排查了问题 能不能加你的tg 我在吃饭 一会发给您图片


naiba <notifications@github.com>于2021年1月18日 周一下午12:18写道：

**Comment by naiba** [comment]
不用tg，issue可以传图，在输入框下面

**Comment by Antake2333** [comment]
![image](https://user-images.githubusercontent.com/71773494/104876319-6b95aa80-5992-11eb-9f45-48c1c49d75dc.png)
![image](https://user-images.githubusercontent.com/71773494/104876387-8e27c380-5992-11eb-8136-6649cec3c6dc.png)
麻烦你了。新手不太懂，之前的版本没有出问题，可能是有些地方没注意到

**Comment by naiba** [comment]
修复了 更新面板

**Comment by Antake2333** [comment]
thanks boss
