### ISSUE TITLE
登录github出现，访问受限，错误信息:非法的登录方式

### ISSUE THREAD

**Issue by creazytom** [naiba/nezha#7]
用宝塔反代之后，访问域名:8008，登录github出现，访问受限，错误信息:非法的登录方式

**Comment by naiba** [comment]
管理员ID设置的不对，可以重新安装，复制头像图片连接 https://avatars2.githubusercontent.com/u/17063787?s=88&v=4 ，取 17063787 填入安装脚本

**Comment by naiba** [comment]
宝塔反代怎么设置的，反代 ip:8008？要改 GitHub Oauth2 应用里面的 callback

**Comment by creazytom** [comment]
> 宝塔反代怎么设置的，反代 ip:8008？要改 GitHub Oauth2 应用里面的 callback

这样啊

**Comment by naiba** [comment]
没问题回来把issue关了
