### ISSUE TITLE
添加telegram机器人就出现504

### ISSUE THREAD

**Issue by love2wind** [naiba/nezha#70]
RT，一直504怎么破

**Comment by naiba** [comment]
兄弟，你这issue描述的是什么鬼？是面板API 504 还是 tg 接口返回的 504 还是 什么 504？

**Comment by haitau** [comment]
有没有先在telegram里面与你自己创建的机器人先对话？

**Comment by love2wind** [comment]
> 有没有先在telegram里面与你自己创建的机器人先对话？

有的啊，我试了，在浏览器直接打开api链接可以返回正常消息，在哪吒面板设置里添加通知就错误了

**Comment by love2wind** [comment]
> 兄弟，你这issue描述的是什么鬼？是面板API 504 还是 tg 接口返回的 504 还是 什么 504？
是tg接口返回504

**Comment by naiba** [comment]
tg接口504那就是你配置问题了，等楼上回复，是他提供的

**Comment by haitau** [comment]
你直接在浏览器里面输入你的链接 （注意替换相关值）:
https://api.telegram.org/botXXXXXX/sendMessage?chat_id=YYYYYY&text=testmessagesend
看看你telegram能不能收到消息。如是这里报出504，那就检查你的机器人token和你的telegram userid 对不对

**Comment by haitau** [comment]
> > 有没有先在telegram里面与你自己创建的机器人先对话？
> 
> 有的啊，我试了，在浏览器直接打开api链接可以返回正常消息，在哪吒面板设置里添加通知就错误了

能贴一下你的链接么？把你的token和个人id替换成其它文本

**Comment by haitau** [comment]
你先直接在浏览器里面输入 

> > > 有没有先在telegram里面与你自己创建的机器人先对话？
> > 
> > 
> > 有的啊，我试了，在浏览器直接打开api链接可以返回正常消息，在哪吒面板设置里添加通知就错误了
> 
> 能贴一下你的链接么？把你的token和个人id替换成其它文本

面板配置界面，截屏，模糊关键信息。

**Comment by love2wind** [comment]
> 你先直接在浏览器里面输入
> 
> > > > 有没有先在telegram里面与你自己创建的机器人先对话？
> > > 
> > > 
> > > 有的啊，我试了，在浏览器直接打开api链接可以返回正常消息，在哪吒面板设置里添加通知就错误了
> > 
> > 
> > 能贴一下你的链接么？把你的token和个人id替换成其它文本
> 
> 面板配置界面，截屏，模糊关键信息。

![image](https://user-images.githubusercontent.com/11996852/105451973-70bb6800-5cb8-11eb-83a4-89b8efe11c37.png)
https://api.telegram.org/botXXX/sendMessage?chat_id=YYY&text=#NEZHA#
这个链接浏览器中返回400
我把后面的#NEZHA#替换成其他文字在浏览器中就可以返回正确值

**Comment by haitau** [comment]
你这是在国内的vps上部署的吧？有墙，不能连接到telegram服务

**Comment by love2wind** [comment]
> 你这是在国内的vps上部署的吧？有墙，不能连接到telegram服务

香港vps啊

**Comment by haitau** [comment]
提示已经很明显了啊：connect:network is unreachable。 你在vps命令行试试ping 或 curl ，或其它方式验证下vps与telegram的连通性。

**Comment by love2wind** [comment]
> 提示已经很明显了啊：connect:network is unreachable。 你在vps命令行试试ping 或 curl ，或其它方式验证下vps与telegram的连通性。

![image](https://user-images.githubusercontent.com/11996852/105491195-e6dbc100-5cf0-11eb-9fae-84b09217ac40.png)

**Comment by love2wind** [comment]
> 提示已经很明显了啊：connect:network is unreachable。 你在vps命令行试试ping 或 curl ，或其它方式验证下vps与telegram的连通性。

![image](https://user-images.githubusercontent.com/11996852/105491404-33bf9780-5cf1-11eb-9408-37873ca3269c.png)
浏览器发送任意消息都能返回正确的值。
![image](https://user-images.githubusercontent.com/11996852/105491769-d11acb80-5cf1-11eb-95eb-f4ed17c2b8e1.png)
发送#nezha#就会400

**Comment by love2wind** [comment]
> 提示已经很明显了啊：connect:network is unreachable。 你在vps命令行试试ping 或 curl ，或其它方式验证下vps与telegram的连通性。

![image](https://user-images.githubusercontent.com/11996852/105491919-1939ee00-5cf2-11eb-98dc-8779960618c3.png)
能ping通

**Comment by haitau** [comment]
你不觉得这有问题么？ping telegram，返回 facebook，这两个是死对头啊

**Comment by naiba** [comment]
国内机器还是放弃折腾用微信吧

>
