### ISSUE TITLE
希望增加续费提醒

### ISSUE THREAD

**Issue by Antake2333** [naiba/nezha#71]
### 描述问题 Describe the problem
希望增加续费提醒，以免鸡鸡忘记续费

希望增加续费提醒，以免鸡鸡忘记续费
### 期待的结果 Expected result
希望增加续费提醒，以免鸡鸡忘记续费

希望增加续费提醒，以免鸡鸡忘记续费
### 版本环境 Version environment

* 版本 Version：
* 操作系统 Operating system：
* 浏览器（如果使用）Browser (if used)：

**Comment by naiba** [comment]
你这需求……鸡场老板还会放过给你发账单的机会？

**Comment by Antake2333** [comment]
哈哈哈 只留优质鸡

naiba <notifications@github.com>于2021年1月19日 周二下午6:20写道：

**Comment by coreki** [comment]
我觉得这个需求很好，我也需要，就是加上备注功能，自己备注一些：续费日期，价格等，可以不在列表显示出来，但是留一个icon点击就显示自己的一些备注内容。

**Comment by naiba** [comment]
@coreki 续费提醒可以这么做：将定时任务设置为要续费的时间每年6月1号 `* * 1 6 *`，然后命令就填 `whoami`，勾选上推送成功，当前就能收到续费提醒了，可以提前几天。。

工具是死的 人是活的
