### ISSUE TITLE
DayNight主题没有显示统计流量

### ISSUE THREAD

**Issue by KANIKIG** [naiba/nezha#74]
### 描述问题 Describe the problem
新主题很漂亮，但是找不到服务器网卡流量统计在哪。

### 期待的结果 Expected result
希望像原主题一样加上弹出显示信息。

### 版本环境 Version environment
* 版本 Version：0.3.2
* 操作系统 Operating system：centos7
* 浏览器（如果使用）Browser (if used)：

**Comment by naiba** [comment]
@JackieSung4ev
