### ISSUE TITLE
节点已离线

### ISSUE THREAD

**Issue by 5536086** [naiba/nezha#8]
`实时通道建立
可以实时获取最新监控数据啦`

但是，节点都是离线状态

**Comment by naiba** [comment]
套 CDN 或者反代了吗

**Comment by 5536086** [comment]
> 套 CDN 或者反代了吗

没套CDN，用另一台机器的宝塔面板反代面板机器，但是只能反代/目录，没法反代/ws目录呢，不知道是不是这个问题导致的

**Comment by naiba** [comment]
节点离线是因为agent配置不对，如果 id 跟 secret 都没问题只能是 agent 配置的 域名 解析出来不是你面板所在的 ip 了。
或者端口不是你面板配置的rpc端口。

**Comment by 5536086** [comment]
> 节点离线是因为agent配置不对，如果 id 跟 secret 都没问题只能是 agent 配置的 域名 解析出来不是你面板所在的 ip 了。
> 或者端口不是你面板配置的rpc端口。

莫名其妙的解决了，但是不知道具体问题出在哪里

**Comment by naiba** [comment]
agent有自动重连机制，每次重连失败等待双倍时间 1/2/4/8 这样，可能刚刚在等待期

**Comment by 5536086** [comment]
> agent有自动重连机制，每次重连失败等待双倍时间 1/2/4/8 这样，可能刚刚在等待期

我估计是我受控端写的域名写成了反代域名而不是面板所在的域名而导致的

**Comment by 5536086** [comment]
还有两个问题，第一个是国内机器好像装不了被监控端，卡在下载的步骤。第二个问题就是：这个程序是不是和go语言软件有冲突啊？我一台装了go语言软件，后面装了这个，结果那个go语言的软件不见了。运行目录都没了，后面重装都启动不了，端口也没有冲突，不知道啥情况，哎

**Comment by naiba** [comment]
> 还有两个问题，第一个是国内机器好像装不了被监控端，卡在下载的步骤。第二个问题就是：这个程序是不是和go语言软件有冲突啊？我一台装了go语言软件，后面装了这个，结果那个go语言的软件不见了。运行目录都没了，后面重装都启动不了，端口也没有冲突，不知道啥情况，哎

不会有冲突，一键脚本装的都是二进制，不会使用go编译

**Comment by naiba** [comment]
> 第一个是国内机器好像装不了被监控端

后面可能会在国内git服务上建立镜像

**Comment by 5536086** [comment]
> > 还有两个问题，第一个是国内机器好像装不了被监控端，卡在下载的步骤。第二个问题就是：这个程序是不是和go语言软件有冲突啊？我一台装了go语言软件，后面装了这个，结果那个go语言的软件不见了。运行目录都没了，后面重装都启动不了，端口也没有冲突，不知道啥情况，哎
> 
> 不会有冲突，一键脚本装的都是二进制，不会使用go编译

哎，那应该是别的问题导致的，程序目录都不翼而飞了，好让我诧异啊，哈哈
