### ISSUE TITLE
斗胆和奶爸提需求：服务器列表导出和导出，简化客户端录入

### ISSUE THREAD

**Issue by TelBotDev** [naiba/nezha#83]
刚上手，很开心，一下导入了十来个客户端，但是突然发现服务端被自己自己部署在了一个错误的服务器上。
> 要是后台有直接导出配置，就简直太棒了。

发现客户端录入的时候，要填写服务端的IP，Agent ID，还有Agent密钥，这里Agent ID对于客户端好像没啥作用？
> 要是只输入Agent密钥，去掉冗余的Agent ID，录入就更方便了

啥也不懂的萌新提的小小提议，若不合理，奶爸请关闭之。

**Comment by naiba** [comment]
闲下来会考虑做一下

**Comment by Catker** [comment]
> 闲下来会考虑做一下
...个人感觉Agent ID的设定挺好的 对于我这种懒人来说可以保持相同的Agent密钥方便添加机器
