### ISSUE TITLE
DayNight 主题的列表视图一直在波动

### ISSUE THREAD

**Issue by NoToPro** [naiba/nezha#85]
发现列表视图的每列不是对齐的，更让人难受的是还会随着网速变化横向抖动。

不知道怎么用自定义css去把每列固定下来，让他不再抖动（眼花），提一个Issue。

希望奶爸考虑是否修一下这么奇怪的样式？

**Comment by naiba** [comment]
这个不是奶爸维护的哈，主题作者经常会更新，这几天就会发新版，到时关注。
