### ISSUE TITLE
面板配置第二天就会出现500错误

### ISSUE THREAD

**Issue by doutuo** [naiba/nezha#89]
如图所示，隔天就会出现500
然后要重新安装次，填入github的ID和密钥后，恢复正常。
不知道是哪出了问题。

[![yGnwxe.png](https://s3.ax1x.com/2021/02/05/yGnwxe.png)](https://imgchr.com/i/yGnwxe)

**Comment by naiba** [comment]
提供面板日志

**Comment by doutuo** [comment]
请教下，面板日志的路径在哪，我打包下发你

**Comment by naiba** [comment]
脚本里面有这个选项的

**Comment by doutuo** [comment]
那=我下次有出现500我先不重新安装，再发你，现在面板的日志我看了，只有从我刚重新安装时算起

**Comment by doutuo** [comment]
你好，我等了两天，这次都没有出现500错误，和上次唯一区别是，我网站的标题里面没有空格，不知道是不是网站标题有空格会引起这个问题吗？造成config有误？

**Comment by naiba** [comment]
改回有空格的再看
