### ISSUE TITLE
Turn down the time of agent reconnect

### ISSUE THREAD

**Issue by YuyuYuna** [naiba/nezha#90]
Recommend to turn down the time of
 ``delayWhenError = time.Second * 10``
 to 
``delayWhenError = time.Second * 5``
For more faster reconnect

**Comment by YuyuYuna** [comment]
#enhancement

**Comment by naiba** [comment]
你好，

1. 为什么需要在 5 秒后重连？

2. 如果延迟 5 秒在你情景会导致什么后果？
