### ISSUE TITLE
ERROR: readlink /var/lib/docker/overlay2/l/....: no such file or directory

### ISSUE THREAD

**Issue by melodyjerry** [naiba/nezha#92]
### 描述问题 Describe the problem

1. 服务器重启后，重新安装面板端，被提示
```bash
面板配置 修改成功，请稍等重启生效
> 重启并更新面板
Pulling dashboard ... done
ERROR: readlink /var/lib/docker/overlay2/l/TQBP2B5C2H3VCDZ5EBYV: no such file or directory
ERROR: readlink /var/lib/docker/overlay2/l/TQBP2B5C2H3VCDZ5EBYV: no such file or directory
重启失败，可能是因为启动时间超过了两秒，请稍后查看日志信息
```
无论是重新`1安装面板端`，`2修改面板端配置`，都是一样报错

2. `5重启并更新面板`，出现不一样的报错
![image](https://user-images.githubusercontent.com/47730856/107374778-ec277100-6b22-11eb-9b71-d55922fd860c.png)

### 版本环境 Version environment

* 版本 Version：0.4.5
* 操作系统 Operating system：CentOS7.6

**Comment by naiba** [comment]
1. 用的哪个脚本？
2. 建议重启下docker，systemctl restart docker 然后再重新安装面板

**Comment by melodyjerry** [comment]
> 1. 用的哪个脚本？
> 2. 建议重启下docker，systemctl restart docker 然后再重新安装面板

@naiba 还是一样的提示。我再试了卸载docker，还是一样。

**Comment by naiba** [comment]
>用的哪个脚本？

**Comment by naiba** [comment]
> > > 用的哪个脚本？
> 
> `./nezha.sh`

wget 链接。

脚本版本号多少

**Comment by melodyjerry** [comment]
> > > > 用的哪个脚本？
> > 
> > 
> > `./nezha.sh`
> 
> wget 链接。
> 
> 脚本版本号多少

Linux CentOS7.6 下载的脚本是`v0.4.5`
我不使用wget用curl
```bash
curl -L https://raw.githubusercontent.com/naiba/nezha/master/script/install.sh -o nezha.sh && chmod +x nezha.sh
```
