### ISSUE TITLE
无法连接至被监控服务器

### ISSUE THREAD

**Issue by lyryblog** [naiba/nezha#94]
端口已在宝塔面板及服务器放行（5555）
但查看日志显示连接已拒绝，导致服务器一直离线
Feb 14 08:55:58 VM-12-14-centos nezha-agent[3248]: 2021/02/14 08:55:58 client.ReportSystemInfo err: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp xx.xx.xx.xx:5555: connect: connection refused"

**Comment by lyryblog** [comment]
宝塔面板显示端口未使用（只安装了监控端）

**Comment by naiba** [comment]
1. Agent上配置的域名有没有套CDN

2. 在你装面板的机器上执行 `docker ps -a | grep nezha | grep -v grep` 然后截图看一下
