### ISSUE TITLE
启动遇到问题,使用编译的安装

### ISSUE THREAD

**Issue by phrnet** [naiba/nezha#95]
github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (4 handlers)
[GIN-debug] HEAD   /static/*filepath         --> github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (4 handlers)
panic: html/template: pattern matches no files: `resource/template/**/*`

goroutine 24 [running]:
html/template.Must(...)
	/usr/local/go/src/html/template/template.go:372
github.com/gin-gonic/gin.(*Engine).LoadHTMLGlob(0xc0003bfa40, 0xf2d0d7, 0x16)
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:185 +0x36a
github.com/naiba/nezha/cmd/dashboard/controller.ServeWeb(0x50)
	/home/git/nezha/cmd/dashboard/controller/controller.go:111 +0x6e8
created by main.main
	/home/git/nezha/cmd/dashboard/main.go:110 +0x4c

无法启动

### 版本环境 Version environment

* 版本 Version：最新版本
* 操作系统 Operating system：centos7

**Comment by naiba** [comment]
参考dockerfile和安装脚本
