### ISSUE TITLE
报错下载脚本失败，请检查本机能否连接 get.docker.com 可是我有docker啊

### ISSUE THREAD

**Issue by husangou** [naiba/nezha#96]
### 版本环境 Version environment

* 版本 Version：
* 操作系统 Operating system：
* 浏览器（如果使用）Browser (if used)：

**Comment by naiba** [comment]
发一下脚本执行输出

**Comment by husangou** [comment]
解决了 机子问题

**Comment by husangou** [comment]
又出现了新的问题hhhhh搭建完后刚开始正常 突然就登陆不进去后台了 github报错404
![image](https://user-images.githubusercontent.com/79092733/108621169-fdc51e80-7428-11eb-9924-f31427794fdf.png)

**Comment by husangou** [comment]
面板日志
ERROR: The Compose file './docker-compose.yaml' is invalid because:
services.dashboard.ports contains an invalid type, it should be a number, or an object
services.dashboard.ports contains an invalid type, it should be a number, or an object
