### ISSUE TITLE
被监控服务器无法连接，一直重复报错

### ISSUE THREAD

**Issue by ciyekua** [naiba/nezha#97]
被监控服务器日志一直重复以下内容
Feb 21 09:51:39 nezha-agent[30513]: 2021/02/21 09:51:39 Try to reconnect ...
Feb 21 09:51:39 nezha-agent[30513]: 2021/02/21 09:51:39 client.ReportSystemInfo err: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 34.92.x.x:5555: connect: connection refused"
Feb 21 09:51:39 nezha-agent[30513]: 2021/02/21 09:51:39 Error to close connection ...
Feb 21 09:51:46 nezha-agent[30513]: 2021/02/21 09:51:46 reportState error rpc error: code = Canceled desc = grpc: the client connection is closing

5555端口已开放，Agent上配置的域名没有套CDN，agent配置已检查没有填写错误，管理面板 及 Agent 都是最新版本。
请老哥帮忙看看，非常感谢！

**Comment by ciyekua** [comment]
面板机执行docker ps -a | grep nezha | grep -v grep命令截图
![Screenshot_20210221_100418_com server auditor ssh client_edit_213241456757566](https://user-images.githubusercontent.com/79084809/108613376-5c3fcc00-742c-11eb-870e-5509c084bca2.jpg)

**Comment by naiba** [comment]
服务器提供商后台的防火墙开了吗，使用tcpping 检测一下端口是否存活

**Comment by ciye12138** [comment]
> 服务器提供商后台的防火墙开了吗，使用tcpping 检测一下端口是否存活

防火墙开了，端口正常

**Comment by ciyekua** [comment]
> 服务器提供商后台的防火墙开了吗，使用tcpping检测一下端口是否存活

防火墙开了，端口正常

**Comment by naiba** [comment]
加群发ip。
