### ISSUE TITLE
搭建完后刚开始正常 突然就登陆不进去后台了 github报错404

### ISSUE THREAD

**Issue by husangou** [naiba/nezha#98]
### 版本环境 Version environment

* 版本 Version：
* 操作系统 Operating system：
* 浏览器（如果使用）Browser (if used)：

**Comment by husangou** [comment]
![image](https://user-images.githubusercontent.com/79092733/108629415-aab69000-7457-11eb-89da-f44507601fb2.png)
搭建完后刚开始正常后台正常登陆 突然就登陆不进去后台了 github报错404 然后面板日志报错
面板日志
ERROR: The Compose file './docker-compose.yaml' is invalid because:
services.dashboard.ports contains an invalid type, it should be a number, or an object
services.dashboard.ports contains an invalid type, it should be a number, or an object

**Comment by naiba** [comment]
你还真是孜孜不倦啊铁子，加群发一下链接看一下

**Comment by husangou** [comment]
铁汁满员了 我进不去啊

**Comment by wxlost** [comment]
> 铁汁满员了 我进不去啊

如何了。。。我也是好久没用今天更新一下，登录后台404进不去。。蛋疼
