### ISSUE TITLE
centos8安装服务端无反应

### ISSUE THREAD

**Issue by po888375** [naiba/nezha#99]
### 描述问题 Describe the problem
使用最新脚本安装服务端，选择1进行安装，已经安装完成，但是查看docker发现无容器，并且8008和5555没有程序监听，再次运行脚本，选择5，显示哪吒监控 重启成功，再次查看docker ps -a，发现还是没有容器出现。

### 期待的结果 Expected result
想知道原因以及解决办法。

### 版本环境 Version environment

* 版本 Version：0.4.6
* 操作系统 Operating system：centos8
* 浏览器（如果使用）Browser (if used)：

**Comment by naiba** [comment]
执行一下 `sudo curl -L "https://github.com/docker/compose/releases/download/1.28.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose` 然后 `docker-compose -v` 截图

**Comment by po888375** [comment]
> 执行一下 `sudo curl -L "https://github.com/docker/compose/releases/download/1.28.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose` 然后 `docker-compose -v` 截图

大哥，下好了
docker-compose version 1.28.4, build cabd5cfb

**Comment by naiba** [comment]
`cd /opt/nezha/dashboard && docker-compose up -d` 应该就好了，
你 `echo "https://github.com/docker/compose/releases/download/1.25.0/docker-compose-$(uname -s)-$(uname -m)"` 一下我看是不是存在问题

**Comment by po888375** [comment]
> `cd /opt/nezha/dashboard && docker-compose up -d` 应该就好了，
> 你 `echo "https://github.com/docker/compose/releases/download/1.25.0/docker-compose-$(uname -s)-$(uname -m)"` 一下我看是不是存在问题

大佬，这个对国内鸡下载的速度真恐怖，一秒1K

**Comment by po888375** [comment]
> `cd /opt/nezha/dashboard && docker-compose up -d` 应该就好了，
> 你 `echo "https://github.com/docker/compose/releases/download/1.25.0/docker-compose-$(uname -s)-$(uname -m)"` 一下我看是不是存在问题

大哥，可以用了
https://github.com/docker/compose/releases/download/1.25.0/docker-compose-Linux-x86_64

**Comment by naiba** [comment]
👌🏾
